version: '3.2'
services:
  Futngage-mail:
    image: 'sj26/mailcatcher'
    ports:
      - "1080:1080"
      - "1025:1025"

  Futngage-redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  Futngage-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=pombo
      - POSTGRES_PASSWORD=pombo
    ports:
      - "5532:5432"
    volumes:
      - "futngage-db-data:/var/lib/postgresql/data"

volumes:
  futngage-db-data:
