databases:

  - name: FutEngage_database_development
    databaseName: FutEngage_development
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

  - name: FutEngage_database_production
    databaseName: FutEngage_production
    region: ohio
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

services:
  - type: redis
    name: FutEngage_redis_development
    ipAllowList: [ ] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  - type: redis
    name: FutEngage_redis_production
    region: ohio
    plan: starter
    ipAllowList: [ ] # only allow internal connections
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  - type: web
    name: FutEngage_web_development
    env: ruby
    repo: https://github.com/codengage/FutEngage
    buildCommand: "./bin/render-build-web-development.sh"
    startCommand: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    envVars:
      - key: RAILS_ENV
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_NAME
        fromDatabase:
          name: FutEngage_database_development
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: FutEngage_database_development
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: FutEngage_database_development
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: FutEngage_database_development
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: FutEngage_database_development
          property: password
      - key: REDIS_URL
        fromService:
          type: redis
          name: FutEngage_redis_development
          property: connectionString
      - key: RAILS_MAX_THREADS
        sync: false

  - type: web
    name: FutEngage_web_production
    env: ruby
    plan: starter
    region: ohio
    domains:
      - app.FutEngage.io
    repo: https://github.com/codengage/FutEngage
    buildCommand: "bin/render-build-web.sh"
    startCommand: "bin/rails s -p 3000 -b '0.0.0.0'"
    envVars:
      - key: RAILS_ENV
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_NAME
        fromDatabase:
          name: FutEngage_database_production
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: FutEngage_database_production
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: FutEngage_database_production
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: FutEngage_database_production
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: FutEngage_database_production
          property: password
      - key: REDIS_URL
        fromService:
          type: redis
          name: FutEngage_redis_production
          property: connectionString
      - key: RAILS_MAX_THREADS
        sync: false


  - type: worker
    name: FutEngage_worker_development
    env: ruby
    repo: https://github.com/codengage/FutEngage
    buildCommand: "./bin/render-build-sidekiq-development.sh"
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_ENV
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_NAME
        fromDatabase:
          name: FutEngage_database_development
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: FutEngage_database_development
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: FutEngage_database_development
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: FutEngage_database_development
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: FutEngage_database_development
          property: password
      - key: REDIS_URL
        fromService:
          type: redis
          name: FutEngage_redis_development
          property: connectionString
      - key: RAILS_MAX_THREADS
        sync: false

  - type: worker
    name: FutEngage_worker_production
    env: ruby
    region: ohio
    plan: starter
    repo: https://github.com/codengage/FutEngage
    buildCommand: "./bin/render-build-sidekiq.sh"
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_ENV
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_NAME
        fromDatabase:
          name: FutEngage_database_production
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: FutEngage_database_production
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: FutEngage_database_production
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: FutEngage_database_production
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: FutEngage_database_production
          property: password
      - key: REDIS_URL
        fromService:
          type: redis
          name: FutEngage_redis_production
          property: connectionString
      - key: RAILS_MAX_THREADS
        sync: false


